spring.application.name=Vinayaka
spring.main.web-application-type=none
# Database URL is set dynamically by DatabaseConfiguration
spring.datasource.driverClassName=org.sqlite.JDBC

# Hibernate related stuff
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
